PRAGMA FOREIGN_KEYS = ON;

CREATE TABLE Customers(CustomerId INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,Name TEXT NOT NULL,PhoneNo TEXT UNIQUE NOT NULL,CreatedAt TEXT,UpdatedAt TEXT);

CREATE TABLE Challans(ChallanId INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,DesignNo VARCHAR NOT NULL,ChallanDate TEXT NOT NULL,CustomerId INTEGER REFERENCES Customers(CustomerId) NOT NULL,CreatedAt TEXT,UpdatedAt TEXT);

CREATE TABLE ChallanTransactions(ChallanTransactionId INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,ChallanId INTEGER REFERENCES Challans(ChallanId) ON DELETE CASCADE NOT NULL,Diamond INTEGER NOT NULL,Rate REAL NOT NULL,Paper INTEGER NOT NULL,Total REAL,UpdatedAt TEXT);

-- remove tables
-- DROP TABLE Customers;
-- DROP TABLE Challans;
-- DROP TABLE ChallanTransactions;